FROM jacekmarchwicki/android:java7-r24-4-1

MAINTAINER Cheng Yifan "cyf607@gmail.com"

ENV GRADLE_VERSION 2.10

WORKDIR /usr/bin
RUN apt-get install unzip
RUN curl -sLO https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-all.zip && \
  unzip gradle-${GRADLE_VERSION}-all.zip && \
  ln -s gradle-${GRADLE_VERSION} gradle && \
  rm gradle-${GRADLE_VERSION}-all.zip

ENV GRADLE_HOME /usr/bin/gradle
ENV PATH $PATH:$GRADLE_HOME/bin

RUN mkdir /app
WORKDIR /app
